spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test?serverTimezone=KST
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 9900
      timeout: 200
server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    root: info
    com.fcfs.coupon: debug
